config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  path: '',
  path_names: {
    sign_in: 'masuk',
    sign_out: 'keluar',
    sign_up: 'daftar'
  },
  controllers: {
      confirmations: 'users/confirmations',
      #omniauth_callbacks: 'users/omniauth_callbacks',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  
  root to: 'houses#index', only: [:index]
  
  resources :trends, :path => "populer", only: [:index]
  resources :cruises, :path => "jelajah", only: [:index]
  resources :inputs, :path => "unggah", except: :destroy
  
  # Informasi Dasar
  get 'konfirmasi', to: 'basic_informations#email_confirmation_page'
  get 'tentang', to: 'basic_informations#about_us'
  get 'faq', to: 'basic_informations#faq'
  get 'privasi', to: 'basic_informations#privacy_policy'
  get 'carakerja', to: 'basic_informations#how_it_work'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles
    has_many :videos
end

app/models/jwt_blacklist.rb
class JwtBlacklist < ApplicationRecord
    #include Devise::JWT::RevocationStrategies::Blacklist

    #self.table_name = 'jwt_blacklist'
end

app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :user
    belongs_to :notification_type
end

app/models/notification_type.rb
class NotificationType < ApplicationRecord
    has_many :notifications
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :trackable
          
  has_one :user_biography
  has_one :user_coin_point
  has_many :user_mail_histories
  has_many :user_coin_histories, through: :usr_coin_point
  has_many :user_point_histories, through: :usr_coin_point
  has_many :quotes
  has_many :user_interests
  has_many :videos
  has_many :articles
  has_many :notifications
  has_many :user_video_view_histories
  has_many :user_article_view_histories

  accepts_nested_attributes_for :user_coin_point, allow_destroy: true
  accepts_nested_attributes_for :user_biography, allow_destroy: true
  after_create :create_user_coin_point
  after_create :create_user_biography

  def generate_jwt
    JWT.encode({ id: id,
                exp: 60.days.from_now.to_i },
               Rails.application.secrets.secret_key_base)
  end

  def self.generate_username(user_real_name)
    user_name = user_real_name.delete(' ').slice(0..3)
    user_name += Time.now.strftime("%y%m%S").slice(1..6) + rand(10..99).to_s
    if User.where("username = '#{user_name}'").present?
      return user_name += rand(1..99).to_s
    else
      return user_name
    end
  end
end

app/models/user_biography.rb
class UserBiography < ApplicationRecord
    belongs_to :user
end

app/models/user_coin_history.rb
class UserCoinHistory < ApplicationRecord
    belongs_to :user_coin_point
end

app/models/user_coin_point.rb
class UserCoinPoint < ApplicationRecord
    belongs_to :user
    has_many :user_coin_histories
    has_many :user_point_histories
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
    belongs_to :user
end

app/models/user_mail_history.rb
class UserMailHistory < ApplicationRecord
    belongs_to :user
end

app/models/user_point_history.rb
class UserPointHistory < ApplicationRecord
    belongs_to :user_coin_point
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/controllers/cruises_controller.rb
class CruisesController < ApplicationController

    def index
        respond_to do |format|
            format.html
        end
    end

    private
    def video_all
        @video_list = Video.joins(:user, :category).select("videos.id, videos.name as nama_video, videos.url as alamat_video, users.username as nama_kreator, categories.name as kategori, videos.description as deskripsi_video, videos.created_at as tanggal_unggah, videos.view_count as dilihat").where("videos.validasi = 3")
    end
    def top_video
        video_all
        @top_video = @video_list.order(dilihat: :desc).first(10)
    end
    def video_by_topic
        video_all
        @category_list = Category.select("id, category_name").all
        @top_video = @video_list.where(kategori: "a").first(10)
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

    def index
        @video_list = []
        respond_to do |format|
            format.html
        end
    end

end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController

    def index
        @video_list = []
        respond_to do |format|
            format.html
        end
    end

end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController

    def index
        @video_list = []
        respond_to do |format|
            format.html
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/salira/_mastaka.html.haml
.ui.secondary.menu
    .logo_kenca.header
        = image_tag 'pordev', alt: 'logo pordev', class: 'kenca'
    = link_to "Beranda", root_path, class: (current_page?(root_path) ? "item active" : "item")
    = link_to "Jelajah", cruises_path, class: (current_page?(cruises_path) ? "item active" : "item")
    = link_to "Populer", trends_path, class: (current_page?(trends_path) ? "item active" : "item")
    - if current_user.present?
        = link_to "Unggah", inputs_path, class: (current_page?(inputs_path) ? "item active" : "item")
    .milari
        .ui.search
            .ui.left.icon.input.fluid
                = select_tag('milari', option_tags = nil, options = {class: "ui search dropdown fluid", placeholder: "Telusuri"})
                %i.search.icon
            .results
    - if current_user.present?
        .acis
            .poin.search
                .ui.labeled.icon.button.primary.inverted
                    %i.icon
                        = image_tag 'poin', alt: 'poin', class: 'logo_smaller top_ten_percent'
                    = current_user.user_coin_point.point
            .coin.search
                .ui.labeled.icon.button.primary.inverted
                    %i.icon
                        = image_tag 'coin', alt: 'coin', class: 'logo_smaller top_ten_percent'
                    = current_user.user_coin_point.coin
        .inpormasi
            .ui.dropdown.circular.icon.top.right.pointing.button
                %i.icon.bell.outline
                .menu
                    .item
                        notif
        .abdi
            .ui.dropdown.circular.icon.top.right.pointing.button
                %i.icon.user.outline
                .menu
                    .item
                        Profil Saya
                    .item
                        Edit Profil
                    .item
                        Pengaturan
                    .item
                        = link_to('Keluar', destroy_user_session_path, method: :delete)
    - else
        .inpormasi
            .ui.dropdown.circular.icon.top.right.pointing.button
                %i.icon.bell.outline
                .menu
                    .item
                        notif
        .login_header
            = link_to "/daftar" do
                %button.ui.button.primary
                    Bergabung
            = link_to "/masuk" do
                %button.ui.button.primary.inverted
                    Masuk
                
    .kosong

app/views/layouts/salira/_sampean.html.haml
.ui.three.column.grid
    .column
        .sixteen.wide.column
            .logo_kenca.header
                = image_tag 'pordev_putih', alt: 'logo pordev', class: 'logo'
        .sixteen.wide.column
            %p
                Portal Dekave adalah portal yang dapat memenuhi segala kebutuhan jurusan Desain Komunikasi Visual yang meliputi desain grafis, ilustrasi, sinematografi, fotografi dan animasi.
        %br
        .sixteen.wide.column
            %p
                &copy; 2019 - Portal Dekave
    .column
        %h3
            Sosial Media
        .row
            = link_to "http://www.facebook.com/PortalDekave/", target: :_blank do
                %button.ui.circular.basic.inverted.icon.button.white_background
                    %i.facebook.icon.white_text
            = link_to "http://www.instagram.com/portal.dekave/", target: :_blank do
                %button.ui.circular.basic.inverted.icon.button.white_background
                    %i.instagram.icon.white_text
            = link_to "http://www.youtube.com/channel/UCmJ4K5M2kGNt_DPd2RrWqIQ/about", target: :_blank do
                %button.ui.circular.basic.inverted.icon.button.white_background
                    %i.youtube.icon.white_text
            = link_to "http://twitter.com/pdekave/", target: :_blank do
                %button.ui.circular.basic.inverted.icon.button.white_background
                    %i.twitter.icon.white_text
        %br
        .row
            .ui.grid
                .eight.wide.column
                    = link_to carakerja_path do
                        %button.ui.basic.inverted.button.fluid
                            CARA KERJA
                        %br
                    = link_to faq_path do
                        %button.ui.basic.inverted.button.fluid
                            FAQ
                .eight.wide.column
                    = link_to tentang_path do
                        %button.ui.basic.inverted.button.fluid
                            TENTANG KAMI
                        %br
                    = link_to privasi_path do
                        %button.ui.basic.inverted.button.fluid
                            KEBIJAKAN PRIVASI
    .column
        %h3
            Unduh Aplikasi Portal Dekave
        .ui.two.column.grid
            .column.mid
                = link_to "http://play.google.com/store/apps/", target: :_blank do
                    = image_tag 'google-play-badge', alt: 'Google Play Badge', class: 'logo_small'
            .column.mid
                = link_to "http://www.apple.com/id/ios/app-store/", target: :_blank do
                    = image_tag 'apple-store-badge', alt: 'Apple Store Badge', class: 'logo_smaller'